build: false

version: 1.0.{build}

platform:
  - x86
  - x64

environment:
  matrix:
    - PYTHON: 2.7
    - PYTHON: 3.4

init:
  - "ECHO %PYTHON%"
  - cmd: C:\Miniconda.exe /S /D=C:\Miniconda
  - ps: ls C:\Miniconda/Scripts
  - C:\Miniconda\Scripts\conda config --set always_yes yes
  # We need to do this first as other commands may not work with older versions of conda.
  - C:\Miniconda\Scripts\conda update conda
  - C:\Miniconda\Scripts\conda install numpy scipy nose hdf5 --quiet

install:
  - C:\Miniconda\Scripts\pip install .

test_script:
  - C:\Miniconda\Scripts\nosetests
