build: false

version: 1.0.{build}

platform:
  - x86
  - x64

environment:
  matrix:
    - PYTHON: 2.7
    - PYTHON: 3.4

init:
  - "ECHO %PYTHON%"
  - set CONDA=Miniconda
  - if "%PYTHON" == "3.4" (set CONDA=%CONDA%3)
  - if "%PLATFORM%" == "x64" (set CONDA=%CONDA%-x64)
  - set PATH=C:\%CONDA%;C:\%CONDA%\Scripts;%PATH%
  - conda config --set always_yes yes
  # We need to do this first as other commands may not work with older versions of conda.
  - conda update conda
  - conda install numpy scipy nose hdf5 --quiet

install:
  - pip install .

test_script:
  - nosetests
