build: false

version: 1.0.{build}

platform:
  - x86
  - x64

matrix:
  fast_finish: true

environment:
  matrix:
    - PYTHON: 2.7
      HDF5: h5py
    - PYTHON: 2.7
      HDF5:
    - PYTHON: 3.4
      HDF5: h5py
    - PYTHON: 3.4
      HDF5:

init:
  - "ECHO %PYTHON%"
  - ps: if($env:PYTHON -eq "2.7" -and $env:Platform -eq "x64"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda-latest-Windows-x86_64.exe' C:\Miniconda.exe; echo "Done"}
  - ps: if($env:PYTHON -eq "2.7" -and $env:Platform -eq "x86"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda-latest-Windows-x86.exe' C:\Miniconda.exe; echo "Done"}
  - ps: if($env:PYTHON -eq "3.4" -and $env:Platform -eq "x64"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe' C:\Miniconda.exe; echo "Done"}
  - ps: if($env:PYTHON -eq "3.4" -and $env:Platform -eq "x86"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86.exe' C:\Miniconda.exe; echo "Done"}
  - cmd: C:\Miniconda.exe /S /D=C:\Miniconda
  - ps: ls C:\Miniconda/Scripts
  - C:\Miniconda\Scripts\conda config --set always_yes yes
  # We need to do this first as other commands may not work with older versions of conda.
  - C:\Miniconda\Scripts\conda update conda
  - C:\Miniconda\Scripts\conda install -c numpy scipy nose %HDF5% --quiet

install:
  - pip install .

test_script:
  - C:\Miniconda\Scripts\nosetests
